# Generated by Django 5.0.6 on 2024-06-14 11:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('Intern', 'Intern'), ('Entry', 'Entry'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('_type', models.CharField(choices=[('Hybrid', 'Hybrid'), ('Remote', 'Remote'), ('Onsite', 'Onsite')], db_column='type', max_length=255)),
                ('description', models.TextField()),
                ('description_image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_location)),
                ('feedback', models.CharField(choices=[('No Feedback', 'No Feedback'), ('Rejected', 'Rejected'), ('Interview', 'Interview'), ('Offer', 'Offer')], default='No Feedback', max_length=255)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'ordering': ('-created_at',),
            },
        ),
    ]
