# Generated by Django 5.0.6 on 2024-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='_type',
            new_name='type',
        ),
    ]
