# Generated by Django 5.0.6 on 2024-06-14 11:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename__type_application_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.logo_upload_location),
        ),
    ]
