# Generated by Django 5.0.6 on 2024-06-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_application_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='company_logo_uri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description_image_uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
