# Generated by Django 5.0.6 on 2024-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_application_job_link_alter_application_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='feedback',
            field=models.CharField(choices=[('No Feedback', 'No Feedback'), ('Call', 'Call'), ('Rejected', 'Rejected'), ('Interview', 'Interview'), ('Offer', 'Offer')], default='No Feedback', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='job_link',
            field=models.URLField(blank=True, max_length=600, null=True),
        ),
    ]
